remote_theme: pages-themes/cayman@v0.2.0
inject:
  head:
   - <link rel="stylesheet" href="/css/cc-icons.min.css" type="text/css"  />

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one